/**
 * The macOS LaunchAgent that wakes agent waker.
 *
 * launchd runs a job with no shell, no profile and no user PATH, so everything
 * it is told must be an absolute path. That creates the problem this module
 * exists to solve: the obvious absolute path is the Node binary, and under a
 * version manager that path stops existing the next time the user upgrades
 * Node. A plist written in March quietly stops working in April.
 *
 * So launchd is pointed at a small launcher script in a directory agent waker
 * owns, and the launcher holds the paths that move. When they go stale it says
 * so precisely and exits, which `doctor` can then report, instead of the job
 * failing silently every minute.
 */

import { chmod, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import { TIMEOUTS, type ProcessRunner } from "#src/process/runner.js";
import type {
  SchedulerDriver,
  SchedulerInstallConfig,
  SchedulerStatus,
} from "#src/schedulers/contract.js";

/** The launcher's file name; its directory follows XDG like everything else. */
export const LAUNCHER_NAME = "agent-waker-runner";

/** Reverse-DNS, from the repository that publishes this. */
export const DEFAULT_LABEL = "io.github.andreacappadona17.agent-waker";

/** `EX_CONFIG`: the launcher's recorded paths no longer exist. */
const EXIT_STALE_INSTALL = 78;

/** launchctl's "no such process" — the job simply is not loaded. */
const LAUNCHCTL_NO_SUCH_PROCESS = 113;

const PLIST_MODE = 0o644;
const LAUNCHER_MODE = 0o755;

export interface LaunchdOptions {
  readonly runner: ProcessRunner;
  /** Only for the LaunchAgents directory, which macOS fixes at ~/Library. */
  readonly home: string;
  readonly uid: number;
  /**
   * Where to write the launcher.
   *
   * Passed in rather than derived, so it follows the same XDG resolution as
   * every other path this program owns.
   */
  readonly launcherPath: string;
  readonly label?: string;
}

/** XML has five characters it will not take literally. */
function escapeXml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

export interface PlistOptions {
  readonly label: string;
  readonly programArguments: readonly string[];
  readonly intervalSeconds: number;
  readonly logDirectory: string;
}

/** Renders the LaunchAgent property list. */
export function renderPlist(options: PlistOptions): string {
  const args = options.programArguments
    .map((argument) => `    <string>${escapeXml(argument)}</string>`)
    .join("\n");
  const log = (name: string): string =>
    escapeXml(join(options.logDirectory, name));

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${escapeXml(options.label)}</string>
  <key>ProgramArguments</key>
  <array>
${args}
  </array>
  <key>StartInterval</key>
  <integer>${String(options.intervalSeconds)}</integer>
  <!-- So a fresh install does not wait a whole interval before its first tick. -->
  <key>RunAtLoad</key>
  <true/>
  <!-- The structured event log is the real record; these catch a crash that
       happens before logging starts. -->
  <key>StandardOutPath</key>
  <string>${log("launchd.out.log")}</string>
  <key>StandardErrorPath</key>
  <string>${log("launchd.err.log")}</string>
</dict>
</plist>
`;
}

/** Quotes a path for `/bin/sh`, which is the only escaping this script needs. */
function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

/**
 * Renders the launcher launchd actually invokes.
 *
 * Deliberately `/bin/sh` and deliberately tiny: it reads no profile, inherits
 * no PATH, and does exactly one thing. If what it was told to run has moved,
 * it says which path is missing and exits with a code that means "the
 * configuration is wrong", rather than looking like a provider failure.
 */
export function renderLauncher(config: SchedulerInstallConfig): string {
  const node = shellQuote(config.nodePath);
  const entry = shellQuote(config.entrypoint);
  const xdg = Object.entries(config.xdg ?? {})
    .map(([name, value]) => `export ${name}=${shellQuote(value)}`)
    .join("\n");

  return `#!/bin/sh
# Generated by agent-waker. Do not edit; reinstall the scheduler instead.
#
# launchd points at this file rather than at the interpreter, because a Node
# version manager moves the interpreter and would leave the job pointing at
# nothing.

NODE=${node}
ENTRY=${entry}
${xdg}

if [ ! -x "$NODE" ]; then
  echo "agent-waker: the recorded Node interpreter is gone: $NODE" >&2
  echo "agent-waker: run 'agent-waker doctor' after a Node upgrade." >&2
  exit ${String(EXIT_STALE_INSTALL)}
fi

if [ ! -f "$ENTRY" ]; then
  echo "agent-waker: the recorded entry point is gone: $ENTRY" >&2
  echo "agent-waker: reinstall agent-waker, then 'agent-waker doctor'." >&2
  exit ${String(EXIT_STALE_INSTALL)}
fi

exec "$NODE" "$ENTRY" tick
`;
}

/** Creates the macOS scheduler driver. */
export function createLaunchdScheduler(
  options: LaunchdOptions,
): SchedulerDriver {
  const { runner, home, uid, launcherPath, label = DEFAULT_LABEL } = options;

  const plistPath = join(home, "Library", "LaunchAgents", `${label}.plist`);
  const domain = `gui/${String(uid)}`;

  const launchctl = (
    args: readonly string[],
  ): ReturnType<ProcessRunner["run"]> =>
    runner.run({
      executable: "/bin/launchctl",
      args: [...args],
      timeoutMs: TIMEOUTS.detect,
    });

  /** Unloads the job, treating "it was not loaded" as success. */
  const bootout = async (): Promise<void> => {
    await launchctl(["bootout", `${domain}/${label}`]);
  };

  const readPlist = async (): Promise<string | undefined> =>
    readFile(plistPath, "utf8").catch(() => undefined);

  return {
    async install(config: SchedulerInstallConfig): Promise<void> {
      await mkdir(dirname(launcherPath), { recursive: true });
      await writeFile(launcherPath, renderLauncher(config), "utf8");
      await chmod(launcherPath, LAUNCHER_MODE);

      await mkdir(join(home, "Library", "LaunchAgents"), { recursive: true });
      await writeFile(
        plistPath,
        renderPlist({
          label,
          programArguments: [launcherPath],
          intervalSeconds: config.intervalSeconds,
          logDirectory: config.logDirectory,
        }),
        "utf8",
      );
      await chmod(plistPath, PLIST_MODE);

      // Ask macOS whether it can read what was just written. A plist only this
      // program can parse is a job that never runs, discovered days later.
      const lint = await runner.run({
        executable: "/usr/bin/plutil",
        args: ["-lint", plistPath],
        timeoutMs: TIMEOUTS.detect,
      });

      if (lint.exitCode !== 0) {
        throw new Error(
          `The generated plist is not valid: ${lint.stdout.trim() || lint.stderr.trim()}`,
        );
      }

      // Unload first, so installing over an existing job is an update rather
      // than a conflict. A job that was not loaded makes this a no-op.
      await bootout();

      const load = await launchctl(["bootstrap", domain, plistPath]);

      if (load.exitCode !== 0) {
        throw new Error(
          `launchctl refused to load the job: ${load.stderr.trim() || load.stdout.trim()}`,
        );
      }
    },

    async inspect(): Promise<SchedulerStatus> {
      const plist = await readPlist();

      if (plist === undefined) {
        return {
          installed: false,
          loaded: false,
          stalePath: false,
          plistPath,
          launcherPath,
        };
      }

      const printed = await launchctl(["print", `${domain}/${label}`]);
      const interval =
        /<key>StartInterval<\/key>\s*<integer>(\d+)<\/integer>/.exec(
          plist,
        )?.[1];
      // The plist names a launcher; if that file is gone the job is installed
      // and broken, which is a different thing from not installed.
      const launcherPresent = await readFile(launcherPath, "utf8").then(
        () => true,
        () => false,
      );

      return {
        installed: true,
        loaded: printed.exitCode === 0,
        stalePath: !launcherPresent,
        plistPath,
        launcherPath,
        ...(interval === undefined
          ? {}
          : { intervalSeconds: Number(interval) }),
      };
    },

    async uninstall(): Promise<void> {
      const result = await launchctl(["bootout", `${domain}/${label}`]);

      // The files go either way: a half-removed install is worse than both of
      // the states it sits between.
      await rm(plistPath, { force: true });
      await rm(launcherPath, { force: true });

      // "No such process" only means it was not loaded, which is the outcome
      // being asked for. Anything else left a job running that now has no
      // plist behind it, and the user needs to hear about it.
      if (
        result.exitCode !== 0 &&
        result.exitCode !== LAUNCHCTL_NO_SUCH_PROCESS
      ) {
        throw new Error(
          `The scheduler files were removed, but launchctl could not unload the job: ${result.stderr.trim() || result.stdout.trim()}`,
        );
      }
    },
  };
}
