/** The stable launcher and recorded-path health shared by native schedulers. */
import { constants } from "node:fs";
import { access, readFile, realpath, stat } from "node:fs/promises";
import { isNvmNodePath } from "#src/process/discovery.js";
import type {
  SchedulerInstallConfig,
  SchedulerStatus,
} from "#src/schedulers/contract.js";

export const LAUNCHER_NAME = "agent-waker-runner";
const EXIT_STALE_INSTALL = 78;

/** Quotes a path for `/bin/sh`, which is the only escaping this script needs. */
function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

/** Read only the literal assignments we generate; never evaluate a shell. */
function recordedPath(
  launcher: string,
  name: "NODE" | "ENTRY",
): string | undefined {
  const quoted = new RegExp(
    String.raw`^${name}=('(?:[^']|'\\'')*')$`,
    "m",
  ).exec(launcher)?.[1];
  if (quoted === undefined) return undefined;
  const value = quoted.slice(1, -1).replaceAll("'\\''", "'");
  return shellQuote(value) === quoted && value.startsWith("/")
    ? value
    : undefined;
}

async function usableFile(
  path: string | undefined,
  executable = false,
): Promise<boolean> {
  if (path === undefined) return false;
  try {
    if (!(await stat(path)).isFile()) return false;
    await access(path, executable ? constants.X_OK : constants.R_OK);
    return true;
  } catch {
    return false;
  }
}

/**
 * Renders the launcher the native scheduler actually invokes.
 *
 * Deliberately `/bin/sh` and deliberately tiny: it reads no profile, inherits
 * no PATH, and does exactly one thing. If what it was told to run has moved,
 * it says which path is missing and exits with a code that means "the
 * configuration is wrong", rather than looking like a provider failure.
 */
export function renderLauncher(config: SchedulerInstallConfig): string {
  const node = shellQuote(config.nodePath);
  const entry = shellQuote(config.entrypoint);
  const xdg = Object.entries(config.xdg ?? {})
    .map(([name, value]) => `export ${name}=${shellQuote(value)}`)
    .join("\n");

  return `#!/bin/sh
# Generated by agent-waker. Do not edit; reinstall the scheduler instead.
#
# The scheduler points at this file rather than at the interpreter, because a Node
# version manager moves the interpreter and would leave the job pointing at
# nothing.

NODE=${node}
ENTRY=${entry}
${xdg}

if [ ! -x "$NODE" ]; then
  echo "agent-waker: the recorded Node interpreter is gone: $NODE" >&2
  echo "agent-waker: run 'agent-waker doctor' after a Node upgrade." >&2
  exit ${String(EXIT_STALE_INSTALL)}
fi

if [ ! -f "$ENTRY" ]; then
  echo "agent-waker: the recorded entry point is gone: $ENTRY" >&2
  echo "agent-waker: reinstall agent-waker, then 'agent-waker doctor'." >&2
  exit ${String(EXIT_STALE_INSTALL)}
fi

exec "$NODE" "$ENTRY" tick
`;
}

/** The same recorded-path health checks for every native scheduler. */
export async function inspectLauncher(
  launcherPath: string,
): Promise<
  Pick<
    SchedulerStatus,
    | "stalePath"
    | "staleReason"
    | "nodePath"
    | "entrypoint"
    | "nodeManagedByNvm"
    | "entrypointManagedByNvm"
  >
> {
  const launcher = await readFile(launcherPath, "utf8").catch(() => "");
  const nodePath = recordedPath(launcher, "NODE");
  const entrypoint = recordedPath(launcher, "ENTRY");
  const resolvedNode =
    nodePath === undefined
      ? ""
      : await realpath(nodePath).catch(() => nodePath);
  const resolvedEntry =
    entrypoint === undefined
      ? ""
      : await realpath(entrypoint).catch(() => entrypoint);
  const usable = await Promise.all([
    usableFile(launcherPath, true),
    usableFile(nodePath, true),
    usableFile(entrypoint),
  ]);
  const staleReason =
    !usable[0] || nodePath === undefined || entrypoint === undefined
      ? "launcher"
      : !usable[1]
        ? "node"
        : !usable[2]
          ? "entrypoint"
          : undefined;
  return {
    stalePath: usable.includes(false),
    ...(staleReason === undefined ? {} : { staleReason }),
    ...(nodePath === undefined ? {} : { nodePath }),
    ...(entrypoint === undefined ? {} : { entrypoint }),
    nodeManagedByNvm:
      isNvmNodePath(nodePath ?? "") || isNvmNodePath(resolvedNode),
    entrypointManagedByNvm:
      isNvmNodePath(entrypoint ?? "") || isNvmNodePath(resolvedEntry),
  };
}
